In [4]:
import json

f = open("/lustre/fswork/projects/rech/dki/ujo91el/code/DSI_LIDAR_HD/dictio_results/results_dsi3d_east_global.json") 
first_ranking = json.load(f)
f.close()

In [6]:
first_ranking

[{'query_idx': 0,
  'Top10_id': ['/lustre/fsn1/worksf/projects/rech/dki/ujo91el/datas/lidarhd_v2/bin/LHD_FXX_0656_6860_PTS_O_LAMB93_IGN69.copc_2_12_46.bin',
   '/lustre/fsn1/worksf/projects/rech/dki/ujo91el/datas/lidarhd_v2/bin/LHD_FXX_0656_6860_PTS_O_LAMB93_IGN69.copc_27_10_46.bin',
   '/lustre/fsn1/worksf/projects/rech/dki/ujo91el/datas/lidarhd_v2/bin/LHD_FXX_0656_6860_PTS_O_LAMB93_IGN69.copc_29_9_46.bin',
   '/lustre/fsn1/worksf/projects/rech/dki/ujo91el/datas/lidarhd_v2/bin/LHD_FXX_0656_6860_PTS_O_LAMB93_IGN69.copc_18_13_46.bin',
   '/lustre/fsn1/worksf/projects/rech/dki/ujo91el/datas/lidarhd_v2/bin/LHD_FXX_0656_6860_PTS_O_LAMB93_IGN69.copc_2_5_47.bin',
   '/lustre/fsn1/worksf/projects/rech/dki/ujo91el/datas/lidarhd_v2/bin/LHD_FXX_0656_6860_PTS_O_LAMB93_IGN69.copc_14_5_47.bin',
   '/lustre/fsn1/worksf/projects/rech/dki/ujo91el/datas/lidarhd_v2/bin/LHD_FXX_0656_6860_PTS_O_LAMB93_IGN69.copc_20_13_46.bin',
   '/lustre/fsn1/worksf/projects/rech/dki/ujo91el/datas/lidarhd_v2/bin/LHD_FXX_

In [5]:
#src_data = np.load(os.path.join(chemain_stokage_fichier ,f"descripteur_D3Feat/{file_rotation}/{src_name}.npz"))
import numpy as np
import os
src_data = np.load("/lustre/fsn1/projects/rech/dki/ujo91el/descripteur_D3Feat/rotation/LHD_FXX_0656_6860_PTS_O_LAMB93_IGN69.copc_10_10_46.npz")


In [12]:
src_data

NpzFile '/lustre/fsn1/projects/rech/dki/ujo91el/descripteur_D3Feat/rotation/LHD_FXX_0656_6860_PTS_O_LAMB93_IGN69.copc_10_10_46.npz' with keys: keypts, features, scores

In [13]:
scores = src_data["scores"].reshape(-1)

In [15]:
len(scores)

91223

In [18]:
top_keypts = src_data["keypts"][top_indices]
top_scores = src_data["scores"][top_indices]

coord_point = top_keypts    

In [20]:
top_scores

array([[0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.69314647],
       [0.693

In [6]:
def d3feat_call(filepath, top_k = 300):
    src_data = np.load(filepath)
    scores = src_data["scores"].reshape(-1)
    
    top_k = min(top_k, len(scores))
    top_indices = np.argsort(scores)[-top_k:]

    top_keypts = src_data["keypts"][top_indices]
    top_scores = src_data["scores"][top_indices]
    
    coord_point = top_keypts   
    return coord_point

In [7]:
d3feat_call("/lustre/fsn1/projects/rech/dki/ujo91el/descripteur_D3Feat/rotation/LHD_FXX_0656_6860_PTS_O_LAMB93_IGN69.copc_10_10_46.npz", top_k = 300)

array([[232.32, 238.19,  49.48],
       [242.82, 209.73,  62.79],
       [232.44, 239.54,  49.47],
       [232.46, 239.1 ,  49.39],
       [237.45, 181.27,  49.95],
       [233.28, 245.28,  49.4 ],
       [231.96, 233.97,  49.46],
       [237.23, 235.65,  49.43],
       [237.28, 235.12,  49.44],
       [232.69, 238.81,  49.37],
       [241.29, 236.97,  49.93],
       [233.5 , 244.97,  49.38],
       [241.25, 238.07,  49.93],
       [169.44, 234.14,  49.68],
       [240.95, 237.88,  49.92],
       [236.91, 186.81,  49.9 ],
       [237.17, 180.61,  49.9 ],
       [232.15, 238.85,  49.53],
       [237.16, 181.39,  49.91],
       [236.7 , 180.34,  49.87],
       [236.79, 180.76,  49.88],
       [233.05, 245.03,  49.41],
       [233.03, 238.96,  49.37],
       [241.53, 236.98,  49.97],
       [236.79, 187.34,  49.9 ],
       [241.74, 237.67,  49.95],
       [161.21, 258.66,  49.51],
       [219.66, 172.78,  49.47],
       [164.81, 245.8 ,  49.65],
       [255.93, 251.52,  50.23],
       [25

In [11]:
local_embeddings_D3feat = d3feat_call("/lustre/fsn1/projects/rech/dki/ujo91el/descripteur_D3Feat/rotation/LHD_FXX_0656_6860_PTS_O_LAMB93_IGN69.copc_10_10_46.npz", top_k = 300)

import torch 

max_points = 20000

local_embeddings ={}
if torch.cuda.is_available():
    coord_embeddings_D3feat = torch.from_numpy(local_embeddings_D3feat).unsqueeze(0).cuda()
    coordoner_point_LoGG3D = local_embeddings_LoGG3D['keypoints'].unsqueeze(0).cuda()
else:
    coord_embeddings_D3feat = torch.from_numpy(local_embeddings_D3feat).unsqueeze(0).to(torch.device("cpu"))
    coordoner_point_LoGG3D = local_embeddings_LoGG3D['keypoints'].unsqueeze(0).to(torch.device("cpu"))

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [10]:
coord_embeddings_D3feat

tensor([[[232.3200, 238.1900,  49.4800],
         [242.8200, 209.7300,  62.7900],
         [232.4400, 239.5400,  49.4700],
         [232.4600, 239.1000,  49.3900],
         [237.4500, 181.2700,  49.9500],
         [233.2800, 245.2800,  49.4000],
         [231.9600, 233.9700,  49.4600],
         [237.2300, 235.6500,  49.4300],
         [237.2800, 235.1200,  49.4400],
         [232.6900, 238.8100,  49.3700],
         [241.2900, 236.9700,  49.9300],
         [233.5000, 244.9700,  49.3800],
         [241.2500, 238.0700,  49.9300],
         [169.4400, 234.1400,  49.6800],
         [240.9500, 237.8800,  49.9200],
         [236.9100, 186.8100,  49.9000],
         [237.1700, 180.6100,  49.9000],
         [232.1500, 238.8500,  49.5300],
         [237.1600, 181.3900,  49.9100],
         [236.7000, 180.3400,  49.8700],
         [236.7900, 180.7600,  49.8800],
         [233.0500, 245.0300,  49.4100],
         [233.0300, 238.9600,  49.3700],
         [241.5300, 236.9800,  49.9700],
         [236.79

In [15]:
embeddings = None
eval_subset = 2
for ndx in range (eval_subset):
    if embeddings is None:
        embeddings = np.zeros((eval_subset, embedding.shape[1]), dtype=embedding.dtype)
    embeddings[ndx] = embedding
    

NameError: name 'embedding' is not defined

In [ ]:
def compute_embedding(self, pc, model, coords, points, is_dense=False):
    """
    Computes global and local embeddings for a point cloud using the provided model.

    Extracts a global descriptor, global embedding, keypoints, and their corresponding feature descriptors
    from the model's output. Handles both dense and sparse point cloud representations.

    Args:
        pc: Input point cloud tensor.
        model: The model used to compute embeddings.
        coords: Coordinates of the point cloud.
        points: Points of the point cloud.
        is_dense (bool): If True, treats the point cloud as dense. Defaults to False.

    Returns:
        tuple: (global_descriptor, global_embedding, keypoints, key_embeddings)
            - global_descriptor (np.ndarray): Global descriptor of the point cloud.
            - global_embedding (np.ndarray): Global embedding reshaped as (1, D).
            - keypoints (torch.Tensor): (N, 3) array of keypoints.
            - key_embeddings (torch.Tensor): (N, D) array of keypoint feature descriptors.
    """


    output_desc, output_feats, xc = model(pc)
    
    if is_dense:

        output_features = output_feats.cpu().detach().numpy()
        output_points = points
    else:
        xc_coords = xc.C
        
        xc_feat = xc.F.cpu().detach().numpy()
        _, xc_counts = torch.unique(xc_coords[:, -1], return_counts=True)
        y = torch.split(xc_coords, list(xc_counts))

        assert len(y) == 1

        xc_coords = xc_coords.cpu().detach().numpy()
        xc_coords= xc_coords[:,:3]
        len_coords = len(coords)
        all_coords = np.vstack((coords,xc_coords))
        all_hash_vals = ravel_hash(all_coords)

        dense_hash = all_hash_vals[:len_coords]
        coarse_hash = all_hash_vals[len_coords:]

        sorter = np.argsort(dense_hash)
        xc_hash_inds = sorter[np.searchsorted(dense_hash, coarse_hash, sorter=sorter)]

        unique_xc_hash_inds, unique_xc_hash_inds_indices = np.unique(xc_hash_inds,
                                            return_index=True)
        

        output_points = points[unique_xc_hash_inds]
        output_features = xc_feat[unique_xc_hash_inds_indices]

    global_descriptor = output_desc.cpu().detach().numpy()


    global_embedding = np.reshape(global_descriptor, (1, -1))

    
    return global_descriptor ,global_embedding, torch.tensor(output_points, dtype=torch.float), torch.tensor(output_features, dtype=torch.float)


In [ ]:


            
        print(coordoner_point_LoGG3D.shape[1])
        distances =  torch.norm((coord_embeddings_D3feat[:, :, None, :] - coordoner_point_LoGG3D[:, None, :, :]), dim=-1)
        mask = distances <= rayon
        mask_ref = mask.any(dim=1)[0]
        selected_keypoints = local_embeddings_LoGG3D['keypoints'][mask_ref]
        selected_features = local_embeddings_LoGG3D['features'][mask_ref]

        torch.manual_seed(42)
        # Limitation à max_points si trop nombreux
        if selected_keypoints.shape[0] > max_points:
            idx = torch.randperm(selected_keypoints.shape[0])[:max_points]
            selected_keypoints = selected_keypoints[idx]
            selected_features = selected_features[idx]

        local_embeddings['keypoints'] = selected_keypoints
        local_embeddings['features'] = selected_features
        return local_embeddings

In [ ]:
if D3Feat == True:
    if k == 0 :
        local_query_embeddings_LoGG3D = self.compute_embeddings(self.eval_set.query_set, model, id_nom =id_query)
        coord_D3Feat_query = self.D3feat_fonction(self.eval_set.query_set , id_query , file_rotation ,nb_clusteur,MEAN_SHIFT_p ,bandwidth )

        local_query_embeddings_modif = self.program_selection_point(coord_D3Feat_query ,local_query_embeddings_LoGG3D,rayon,min_num_feat)
        



    
    local_map_embeddings_LoGG3D = self.compute_embeddings(self.eval_set.map_set, model, id_nom = k_id) 
    coord_D3Feat_map = self.D3feat_fonction(self.eval_set.map_set , k_id , file_rotation ,nb_clusteur,MEAN_SHIFT_p , bandwidth)                 
    local_map_embeddings_modif = self.program_selection_point(coord_D3Feat_map ,local_map_embeddings_LoGG3D,rayon,min_num_feat)

    print(len(local_query_embeddings_modif['keypoints']))
    print(len(local_map_embeddings_modif['keypoints']))
    if visualisation == True  :
        nom_dossier = os.path.join(self.dataset_root, self.eval_set.query_set[id_query].rel_scan_filepath)
        conf_val = sgv_visu.sgv_fn(local_query_embeddings_modif, local_map_embeddings_modif,local_query_embeddings_LoGG3D,local_map_embeddings_LoGG3D,D3Feat,k,nom_dossier,name_file_visu, d_thresh=d_thresh ,min_num_feat = min_num_feat)
    else :
        conf_val = sgv_utils.sgv_fn(local_query_embeddings_modif, local_map_embeddings_modif,D3Feat, d_thresh=d_thresh , min_num_feat = min_num_feat)