In [1]:
import numpy as np

In [2]:
1+1

2

In [3]:
import json

In [4]:
dict_link = "/lustre/fswork/projects/rech/dki/ujo91el/code/DSI-3D/results_dsi3d_00_hilbert.json"

In [6]:
dict_link = "/lustre/fswork/projects/rech/dki/ujo91el/code/DSI-3D/results_dsi3d_00_hilbert.json"
with open(dict_link, "r") as f:
    a = json.load(f)
a[0]['query_idx'], a[0]['Top10_id']

In [11]:
a[0]

{'query_idx': 0,
 'Top10_id': ['000001',
  '000002',
  '004448',
  '004449',
  '004447',
  '004452',
  '000003',
  '004446',
  '004404',
  '003913'],
 'dist': [0.8604428872737419,
  1.7197701824069709,
  1.3528799007595158,
  1.7044282242331883,
  1.2284818703564484,
  3.395865733861494,
  2.580207713898336,
  1.3572444523133542,
  14.957964557919734,
  443.45881517277377],
 'score': [0.032832805067300797,
  0.46625420451164246,
  0.5364561676979065,
  1.0482863187789917,
  1.2472258806228638,
  1.4470144510269165,
  1.5304418802261353,
  1.9179887771606445,
  2.440636396408081,
  2.662775754928589],
 'query_pose': [271.2806, 17.60491, 22.29466],
 'place_candidate': [271.23369706, 18.4636041, 22.266260720000002]}

In [12]:
a[0]['query_idx'], a[0]['Top10_id']

(0,
 ['000001',
  '000002',
  '004448',
  '004449',
  '004447',
  '004452',
  '000003',
  '004446',
  '004404',
  '003913'])

In [1]:
#Paris Est exhaustive
import json
with open('/lustre/fsn1/worksf/projects/rech/dki/ujo91el/datas/lidarhd_v2/distances_grid_256_desc_2025-06-23_11-22-13_run_0_4_small_False.json') as f:  
    distances = json.load(f)

In [2]:
#Paris West exhaustive
import json
with open('/lustre/fsn1/worksf/projects/rech/dki/ujo91el/datas/lidarhd_v3/distances_grid_256_desc_2025-06-23_11-22-13_run_0_4.json') as f: 
   distances = json.load(f)

In [3]:
distances

{'/lustre/fsn1/worksf/projects/rech/dki/ujo91el/datas/lidarhd_v3/bin/LHD_FXX_0647_6864_PTS_O_LAMB93_IGN69.copc_41_24_39.bin': [0.0,
  '/lustre/fsn1/worksf/projects/rech/dki/ujo91el/datas/lidarhd_v3/bin/LHD_FXX_0646_6864_PTS_O_LAMB93_IGN69.copc_28_13_40.bin'],
 '/lustre/fsn1/worksf/projects/rech/dki/ujo91el/datas/lidarhd_v3/bin/LHD_FXX_0646_6864_PTS_O_LAMB93_IGN69.copc_23_15_39.bin': [0.0,
  '/lustre/fsn1/worksf/projects/rech/dki/ujo91el/datas/lidarhd_v3/bin/LHD_FXX_0645_6862_PTS_O_LAMB93_IGN69.copc_29_36_42.bin'],
 '/lustre/fsn1/worksf/projects/rech/dki/ujo91el/datas/lidarhd_v3/bin/LHD_FXX_0646_6864_PTS_O_LAMB93_IGN69.copc_4_19_39.bin': [0.0,
  '/lustre/fsn1/worksf/projects/rech/dki/ujo91el/datas/lidarhd_v3/bin/LHD_FXX_0647_6862_PTS_O_LAMB93_IGN69.copc_1_9_44.bin'],
 '/lustre/fsn1/worksf/projects/rech/dki/ujo91el/datas/lidarhd_v3/bin/LHD_FXX_0645_6862_PTS_O_LAMB93_IGN69.copc_3_12_44.bin': [0.0,
  '/lustre/fsn1/worksf/projects/rech/dki/ujo91el/datas/lidarhd_v3/bin/LHD_FXX_0647_6861_PTS_

In [1]:
# Pickle

In [3]:
# Load evaluation set from the pickle
import pickle
pickle_filepath = "/lustre/fswork/projects/rech/dki/ujo91el/code/SpectralGV_D3Feat/SpectralGV-main/datasets/lidar/file_traitment.pickle"
query_l, map_l = pickle.load(open(pickle_filepath, 'rb'))

In [4]:
query_l

[(4683,
  '/lustre/fsn1/worksf/projects/rech/dki/ujo91el/datas/lidarhd_v2/bin/LHD_FXX_0657_6861_PTS_O_LAMB93_IGN69.copc_0_0_45.bin',
  array([1010., 1010.]),
  array([[1.00e+00, 0.00e+00, 0.00e+00, 1.01e+03],
         [0.00e+00, 1.00e+00, 0.00e+00, 1.01e+03],
         [0.00e+00, 0.00e+00, 1.00e+00, 1.00e+02],
         [0.00e+00, 0.00e+00, 0.00e+00, 1.00e+00]])),
 (764,
  '/lustre/fsn1/worksf/projects/rech/dki/ujo91el/datas/lidarhd_v2/bin/LHD_FXX_0657_6861_PTS_O_LAMB93_IGN69.copc_0_0_46.bin',
  array([1010., 1010.]),
  array([[1.00e+00, 0.00e+00, 0.00e+00, 1.01e+03],
         [0.00e+00, 1.00e+00, 0.00e+00, 1.01e+03],
         [0.00e+00, 0.00e+00, 1.00e+00, 1.00e+02],
         [0.00e+00, 0.00e+00, 0.00e+00, 1.00e+00]])),
 (11694,
  '/lustre/fsn1/worksf/projects/rech/dki/ujo91el/datas/lidarhd_v2/bin/LHD_FXX_0657_6861_PTS_O_LAMB93_IGN69.copc_0_10_44.bin',
  array([1010., 1210.]),
  array([[1.00e+00, 0.00e+00, 0.00e+00, 1.01e+03],
         [0.00e+00, 1.00e+00, 0.00e+00, 1.21e+03],
         

In [5]:
map_l

[(4683,
  '/lustre/fsn1/worksf/projects/rech/dki/ujo91el/datas/lidarhd_v2/bin/LHD_FXX_0657_6861_PTS_O_LAMB93_IGN69.copc_0_0_45.bin',
  array([1010., 1010.]),
  array([[1.00e+00, 0.00e+00, 0.00e+00, 1.01e+03],
         [0.00e+00, 1.00e+00, 0.00e+00, 1.01e+03],
         [0.00e+00, 0.00e+00, 1.00e+00, 1.00e+02],
         [0.00e+00, 0.00e+00, 0.00e+00, 1.00e+00]])),
 (764,
  '/lustre/fsn1/worksf/projects/rech/dki/ujo91el/datas/lidarhd_v2/bin/LHD_FXX_0657_6861_PTS_O_LAMB93_IGN69.copc_0_0_46.bin',
  array([1010., 1010.]),
  array([[1.00e+00, 0.00e+00, 0.00e+00, 1.01e+03],
         [0.00e+00, 1.00e+00, 0.00e+00, 1.01e+03],
         [0.00e+00, 0.00e+00, 1.00e+00, 1.00e+02],
         [0.00e+00, 0.00e+00, 0.00e+00, 1.00e+00]])),
 (11694,
  '/lustre/fsn1/worksf/projects/rech/dki/ujo91el/datas/lidarhd_v2/bin/LHD_FXX_0657_6861_PTS_O_LAMB93_IGN69.copc_0_10_44.bin',
  array([1010., 1210.]),
  array([[1.00e+00, 0.00e+00, 0.00e+00, 1.01e+03],
         [0.00e+00, 1.00e+00, 0.00e+00, 1.21e+03],
         

ModuleNotFoundError: No module named 'open3d'

In [ ]:
query_set = []
map_set = []
for e in query_l:
    query_set.append(EvaluationTuple(e[0], e[1], e[2], e[3]))
self.map_set = []
for e in map_l:
    map_set.append(EvaluationTuple(e[0], e[1], e[2], e[3]))